# Generated by Django 5.0.6 on 2024-06-01 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_inputfile_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="namedentity",
            name="input_file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.inputfile",
            ),
            preserve_default=False,
        ),
    ]
